name: housework_bot
on:
  workflow_dispatch:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 15 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Create dot env file
      - shell: bash
        run: |
          touch .env
          echo "TWITTER_CONSUMER_API_KEY=${{ secrets.TWITTER_CONSUMER_API_KEY }}" >> .env
          echo "TWITTER_CONSUMER_API_SECRET_KEY=${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> .env
          echo "GIT_USERNAME=${{ secrets.GIT_USERNAME }}" >> .env
          echo "GIT_CLIENT_ID=${{ secrets.GIT_CLIENT_ID }}" >> .env
          echo "GIT_CLIENT_SECRETS=${{ secrets.GIT_CLIENT_SECRETS }}" >> .env
      
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          pip install pytz
          pip install tweepy
          # 必要なパッケージインストール・・・②

      - name: Run script
        run: |
          # 定期実行するファイルを指定。・・・③
          python main.py
